# Generated by Django 2.0.3 on 2018-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False),
        ),
    ]
