# Generated by Django 2.0.3 on 2018-04-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20180415_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default='', max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
