# Generated by Django 2.0.3 on 2018-04-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20180415_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile1', to='ratings.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile2', to='ratings.Profile'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Profile'),
        ),
    ]
